site_name: PyScript

extra_javascript:
    - javascripts/mini-coi.js

theme:
    name: material

    logo: assets/images/pyscript-black.svg

    palette:
        # Palette toggle for automatic mode
        - media: "(prefers-color-scheme)"
          primary: orange
          toggle:
              icon: material/brightness-auto
              name: Switch to light mode

        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          primary: orange
          scheme: default
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          primary: orange
          scheme: slate
          toggle:
              icon: material/brightness-4
              name: Switch to system preference

    features:
        - content.code.copy
        - content.code.annotate

markdown_extensions:
    - attr_list
    - md_in_html
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - admonition
    - pymdownx.details

extra:
  version:
    provider: mike

plugins:
  - mike:
      version_selector: true
      css_dir: css
      javascript_dir: js
      canonical_version: null

nav:
  - Home: index.md
  - Beginning PyScript: beginning-pyscript.md
  - Code of Conduct: conduct.md
  - Contributing: contributing.md
  - Developer Guide: developers.md
  - License: license.md
  - User guide:
    - Introduction: user-guide/index.md
    - What is PyScript?: user-guide/what.md
    - Features: user-guide/features.md
    - First steps: user-guide/first-steps.md
    - Architecture: user-guide/architecture.md
    - Configuration: user-guide/configuration.md
    - The DOM: user-guide/dom.md
    - Workers: user-guide/workers.md
    - Builtin helpers: user-guide/builtins.md
    - Python terminal: user-guide/terminal.md
    - Plugins: user-guide/plugins.md
    - Example apps: user-guide/examples.md
